-- Add migration script here
CREATE TABLE IF NOT EXISTS "tariff" (
    "name" CHARACTER VARYING(255) NOT NULL PRIMARY KEY,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "role" (
    "name" CHARACTER VARYING(255) NOT NULL PRIMARY KEY,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "default_value" (
	"id" SMALLSERIAL NOT NULL PRIMARY KEY,
	"tariff" CHARACTER VARYING(255) NOT NULL REFERENCES "tariff" ON UPDATE CASCADE ON DELETE RESTRICT,
	"role" CHARACTER VARYING(255) NOT NULL REFERENCES "role" ON UPDATE CASCADE ON DELETE RESTRICT,

	CONSTRAINT chk_only_one_row CHECK ((SELECT COUNT(*) FROM default_values) <= 1)
);

CREATE TABLE IF NOT EXISTS "user" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
    "phone" CHARACTER VARYING(11) NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "tariff" CHARACTER VARYING(255) NOT NULL REFERENCES "tariff" ON UPDATE CASCADE ON DELETE RESTRICT,
	"inn" CHARACTER VARYING(12),
	"snils" CHARACTER VARYING(11),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
);

CREATE UNIQUE INDEX idx_user_email ON "user"("email");
CREATE UNIQUE INDEX idx_user_phone ON "user"("phone");

CREATE TABLE IF NOT EXISTS "service" (
    "name" TEXT NOT NULL PRIMARY KEY,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "employee" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
	"role" CHARACTER VARYING(255) NOT NULL REFERENCES "role" ON UPDATE CASCADE ON DELETE RESTRICT,
	"dismissed" BOOLEAN NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE INDEX idx_employee_email ON "employee"("email");

CREATE TABLE IF NOT EXISTS "employee_specs" (
	"employee_id" BIGSERIAL NOT NULL REFERENCES "employee" ON UPDATE CASCADE ON DELETE CASCADE,
	"service" TEXT NOT NULL REFERENCES "service"("name") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY ("employee_id", "service")
);

CREATE TABLE IF NOT EXISTS "request" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(255) NOT NULL,
	"service" TEXT REFERENCES "service" ON UPDATE CASCADE ON DELETE SET NULL,
	"owner_id" BIGINT NOT NULL REFERENCES "employee" ON UPDATE CASCADE ON DELETE CASCADE,
	"employee_id" BIGINT REFERENCES "employee" ON UPDATE CASCADE ON DELETE RESTRICT,
	"priority" SMALLINT NOT NULL, -- если будет фильтр - добавить индекс
	"desc" TEXT NOT NULL,
	"status" SMALLINT NOT NULL, -- если будет фильтр - добавить индекс
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"desired_at" TIMESTAMPTZ NOT NULL,
	"closed_at" TIMESTAMPTZ
);